#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=32g
#SBATCH --time=01:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
##SBATCH --account=hpcsuppt_613

# which gpu node was used
echo "Running on host" $(hostname)

module purge
eval "$(conda shell.bash hook)"
conda activate torch-env

kernprof -o ${SLURM_JOBID}.lprof -l CIFAR10_ResNet50.py
